image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

  # будем использовать свой скрипт сборки

install:
  build: off
    test_script:
      - shellcheck -V

    - # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-order.jar &

#build_script:
#  - chmod +x gradlew # даем права доступа к файлу gradlew
#  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации
build_script:
  - chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true